port: 8590
use_dev_logger: false

youtube:
  cookies: VAULT->/secret/orca/youtube_cookies

spotify: VAULT->/secret/orca/spotify

vk: VAULT->/secret/orca/vk

yandex_music: VAULT->/secret/orca/yandex_music

db: VAULT->/secret/orca/db_connection_profile

redis: VAULT->/secret/orca/redis_connection_profile
