port: 8590

spotify: FS->.spotify.yaml

db:
  host: 127.0.0.1
  port: 5432
  username: root
  password: local
  db: orca
  ssl: false

redis:
  host: 127.0.0.1
  port: 6379
  username: orca
  password: local
  db: 1
