version: '3'

tasks:
  default:
    cmds:
    - echo "For more information run \"task --summary <task>\""
    - echo "Arguments should be passed using \"task <task> -- <arguments>\""
    - echo ""
    - task --list   # by default if someone runs "task" in project directory it will list all available tasks with descriptions
    silent: true

  tidy:
    desc:    This task tidies go.mod
    summary: |
      This task tidies go.mod
      Dependencies:
      - "go" has to be in PATH
    cmds:
    - go mod tidy
    - go mod vendor

  fmt:
    desc:    This task runs go fmt on whole project
    summary: |
      This task runs go fmt on whole project
      Dependencies:
      - "gofumpt" - `go install mvdan.cc/gofumpt@latest`
    cmds:
    - gofumpt -l -w extractor healthcheck migrations models service spotify store utils vk ytdl main.go

  lint:
    desc:    This task runs go lint tool on the whole project
    summary: |
      This task runs go lint tool on the whole project
      Dependencies:
      - "golangci-lint" - (https://golangci-lint.run/usage/install/#local-installation)
    cmds:
    - task: fmt
    - golangci-lint run -v {{.CLI_ARGS}}

  proto:go:
    desc:    This task runs Go protobuf generator for proto files in proto directory
    summary: |
      This task runs Go protobuf generator for proto files in proto directory
      Dependencies:
      - "protoc" (https://grpc.io/docs/protoc-installation/)
      - "protoc-gen-go" and "protoc-gen-go-grpc" (https://grpc.io/docs/languages/go/quickstart/)
    cmds:
    - protoc --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. proto/orca.proto

  proto:python:
    desc:    This task runs Python protobuf generator for proto files in proto directory
    summary: |
      This task runs Python protobuf generator for proto files in proto directory
      Dependencies:
      - "protoc" (https://grpc.io/docs/protoc-installation/)
    cmds:
    - python -m grpc_tools.protoc --proto_path=proto --python_out=proto_python --pyi_out=proto_python --grpc_python_out=proto_python proto/orca.proto

  proto:
    desc:    This task runs protobuf generator for proto files in proto directory for all related projects
    summary: |
      This task runs protobuf generator for proto files in proto directory
      Dependencies:
      - "protoc" (https://grpc.io/docs/protoc-installation/)
      - "protoc-gen-go" and "protoc-gen-go-grpc" (https://grpc.io/docs/languages/go/quickstart/)
    cmds:
    - task: proto:go
    - task: proto:python

  run:
    desc:    This task runs the server locally
    summary: |
      This task runs the server locally
      Dependencies:
      - "go" has to be in PATH
    cmds:
    - go run .
