name: Update

on:
  push:
    branches:
    - master

jobs:
  update:
    runs-on:
    - self-hosted
    - updater
      # unique label for runner created specifically for this job
      # "update" here is the name of the job
    - ${{github.run_id}}-${{github.run_attempt}}-update

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Save image name
      run: echo "image=orca" >> $GITHUB_ENV

    - name: Save image tag
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build image
      run: docker build -t ${{ env.image }}:${{ env.tag }} .
      env:
        # work around https://github.com/github/vscode-github-actions/issues/222.
        image: ${{ env.image }}
        tag: ${{ env.tag }}

    - name: Run update
      run: >
        docker run --rm
        --name "nomad-update-${{ env.image }}-${{ env.tag }}-${{ github.run_id }}-${{ github.run_attempt }}"
        --add-host "server.global.nomad=host-gateway"
        --env NOMAD_ADDR="https://server.global.nomad:4646"
        --env NOMAD_TOKEN="${{ secrets.NOMAD_TOKEN }}"
        nomad-update:latest ${{ env.image }} ${{ env.image }} ${{ env.tag }}
      env:
        # work around https://github.com/github/vscode-github-actions/issues/222.
        image: ${{ env.image }}
        tag: ${{ env.tag }}
